%include %{_topdir}/SPECS/php-common/apc.inc.spec
%include %{_topdir}/SPECS/php-common/bcmath.inc.spec
%include %{_topdir}/SPECS/php-common/bz2.inc.spec
%include %{_topdir}/SPECS/php-common/calendar.inc.spec
%include %{_topdir}/SPECS/php-common/ctype.inc.spec
%include %{_topdir}/SPECS/php-common/curl.inc.spec
%include %{_topdir}/SPECS/php-common/dba.inc.spec
%include %{_topdir}/SPECS/php-common/exif.inc.spec
%include %{_topdir}/SPECS/php-common/fileinfo.inc.spec
%include %{_topdir}/SPECS/php-common/ftp.inc.spec
%include %{_topdir}/SPECS/php-common/gd.inc.spec
%include %{_topdir}/SPECS/php-common/gearman.inc.spec
%include %{_topdir}/SPECS/php-common/http.inc.spec
%include %{_topdir}/SPECS/php-common/iconv.inc.spec
%include %{_topdir}/SPECS/php-common/igbinary.inc.spec
%include %{_topdir}/SPECS/php-common/imagick.inc.spec
%include %{_topdir}/SPECS/php-common/intl.inc.spec
%include %{_topdir}/SPECS/php-common/json.inc.spec
%include %{_topdir}/SPECS/php-common/libevent.inc.spec
%include %{_topdir}/SPECS/php-common/mbstring.inc.spec
%include %{_topdir}/SPECS/php-common/mongo.inc.spec
%include %{_topdir}/SPECS/php-common/mysql.inc.spec
%include %{_topdir}/SPECS/php-common/pcntl.inc.spec
%include %{_topdir}/SPECS/php-common/pgsql.inc.spec
%include %{_topdir}/SPECS/php-common/phar.inc.spec
%include %{_topdir}/SPECS/php-common/posix.inc.spec
%include %{_topdir}/SPECS/php-common/proctitle.inc.spec
%include %{_topdir}/SPECS/php-common/runkit.inc.spec
%include %{_topdir}/SPECS/php-common/shmop.inc.spec
%include %{_topdir}/SPECS/php-common/simplexml.inc.spec
%include %{_topdir}/SPECS/php-common/soap.inc.spec
%include %{_topdir}/SPECS/php-common/sphinx.inc.spec
%include %{_topdir}/SPECS/php-common/tidy.inc.spec
%include %{_topdir}/SPECS/php-common/tokenizer.inc.spec
%include %{_topdir}/SPECS/php-common/wddx.inc.spec
%include %{_topdir}/SPECS/php-common/xdebug.inc.spec
%include %{_topdir}/SPECS/php-common/xml.inc.spec
%include %{_topdir}/SPECS/php-common/xmlreader.inc.spec
%include %{_topdir}/SPECS/php-common/xmlrpc.inc.spec
%include %{_topdir}/SPECS/php-common/xmlwriter.inc.spec
%include %{_topdir}/SPECS/php-common/xsl.inc.spec
%include %{_topdir}/SPECS/php-common/yaf.inc.spec
%include %{_topdir}/SPECS/php-common/zip.inc.spec