%include %{_topdir}/SPECS/php-common/ext/bcmath.spec
%include %{_topdir}/SPECS/php-common/ext/bz2.spec
%include %{_topdir}/SPECS/php-common/ext/calendar.spec
%include %{_topdir}/SPECS/php-common/ext/ctype.spec
%include %{_topdir}/SPECS/php-common/ext/curl.spec
%include %{_topdir}/SPECS/php-common/ext/dba.spec
%include %{_topdir}/SPECS/php-common/ext/exif.spec
%include %{_topdir}/SPECS/php-common/ext/fileinfo.spec
%include %{_topdir}/SPECS/php-common/ext/ftp.spec
%include %{_topdir}/SPECS/php-common/ext/gd.spec
%include %{_topdir}/SPECS/php-common/ext/gearman.spec
%include %{_topdir}/SPECS/php-common/ext/http.spec
%include %{_topdir}/SPECS/php-common/ext/iconv.spec
%include %{_topdir}/SPECS/php-common/ext/igbinary.spec
%include %{_topdir}/SPECS/php-common/ext/imagick.spec
%include %{_topdir}/SPECS/php-common/ext/intl.spec
%include %{_topdir}/SPECS/php-common/ext/json.spec
%include %{_topdir}/SPECS/php-common/ext/libevent.spec
%include %{_topdir}/SPECS/php-common/ext/mbstring.spec
%include %{_topdir}/SPECS/php-common/ext/mongo.spec
%include %{_topdir}/SPECS/php-common/ext/mysql.spec
%include %{_topdir}/SPECS/php-5.5/ext/opcache.spec
%include %{_topdir}/SPECS/php-common/ext/pcntl.spec
%include %{_topdir}/SPECS/php-common/ext/pgsql.spec
%include %{_topdir}/SPECS/php-common/ext/phar.spec
%include %{_topdir}/SPECS/php-common/ext/posix.spec
%include %{_topdir}/SPECS/php-common/ext/proctitle.spec
%include %{_topdir}/SPECS/php-common/ext/runkit.spec
%include %{_topdir}/SPECS/php-common/ext/shmop.spec
%include %{_topdir}/SPECS/php-common/ext/simplexml.spec
%include %{_topdir}/SPECS/php-common/ext/soap.spec
%include %{_topdir}/SPECS/php-common/ext/sphinx.spec
%include %{_topdir}/SPECS/php-common/ext/tidy.spec
%include %{_topdir}/SPECS/php-common/ext/tokenizer.spec
%include %{_topdir}/SPECS/php-common/ext/wddx.spec
%include %{_topdir}/SPECS/php-common/ext/xdebug.spec
%include %{_topdir}/SPECS/php-common/ext/xml.spec
%include %{_topdir}/SPECS/php-common/ext/xmlreader.spec
%include %{_topdir}/SPECS/php-common/ext/xmlrpc.spec
%include %{_topdir}/SPECS/php-common/ext/xmlwriter.spec
%include %{_topdir}/SPECS/php-common/ext/xsl.spec
%include %{_topdir}/SPECS/php-common/ext/yaf.spec
%include %{_topdir}/SPECS/php-common/ext/zip.spec